import Head from 'next/head'
import { useEffect, useState } from 'react'
import { IQuestionList } from '@/src/types/Questionlist'
import { getQuestions, selectedValue, useAppDispatch, useAppSelector } from '@/src/store/reducers/questionListReducer'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  const dispatch = useAppDispatch()
	const questions = useAppSelector(selectedValue) as IQuestionList
	const getAllQuestions = () => dispatch(getQuestions())

	useEffect(() => {
		getAllQuestions()
	}, [])

  console.log('questions', questions)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Hello world from tailwind!
      </h1>
      <Link href={`single-question/${12}`}>Single Question</Link>
    </>
  )
}
